#!/bin/bash

ls -ltr Library/Caches/Metadata/Safari/History/ \
    | awk '{print $6,$7,$8"\t"$9}' \
    | sed -e 's/https*:%2F%2F//' -e 's/\.webhistory$//' \
    | php -R 'echo urldecode("$argn\n");'
